id: I56728F99
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:59:19.518492
last_modified: 2023-02-09 14:59:19.518589
source_metadata:
  title: 'MSV 1,00: Vinayavastūddāna'
  language: bo
bases:
  0AEF:
    base_file: 0AEF.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
